#!/usr/bin/env python3
"""Regenerate translator/examples.md from the checked pairs in verify/examples/.

    python3 tools/build_examples.py

Every pair shown in examples.md passes verify/check.py (run by --selftest),
so the examples cannot drift from the contract.
"""
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
EX = ROOT / "verify" / "examples"

NOTES = {
    "ex1-plain": "A plain-text call. The request on L0004 is accepted on the very next line by a different speaker, "
                 "so that speaker owns it and \"this week\" comes from the acceptance. \"I'll try\" stays tentative. "
                 "\"I'll be honest\" is listed as not a commitment. \"zero\" (the transcript's hearing of Xero) is left alone.",
    "ex2-teams": "A Teams WebVTT export. Nobody accepts the request on L0001 and nobody is named, so its owner is "
                 "`not in source`. The two-line cue became one line. \"Unknown speaker\" is kept as the label, not guessed.",
    "ex3-nothing": "A call with nothing to map. Every section is still present, and empty.",
}


def main():
    parts = ["# Examples\n",
             "Three input/output pairs showing the contract holding. Each input is shown as the translator reads it "
             "(numbered, with its trigger index). Each output passes `python3 verify/check.py`. These examples are "
             "separate from the test inputs in `inputs/`, so a run on those inputs is not answered by an example.\n",
             "This file is generated by `tools/build_examples.py` from `verify/examples/`.\n"]
    for src in sorted(EX.glob("ex*.*")):
        if src.suffix == ".json":
            continue
        name = src.stem
        numbered = subprocess.run([sys.executable, str(ROOT / "tools" / "number.py"), str(src)],
                                  capture_output=True, text=True, check=True).stdout
        out = json.loads((EX / (name + ".json")).read_text(encoding="utf-8"))
        parts.append("\n## %s\n\n%s\n\nInput (`%s`):\n\n```text\n%s```\n\nOutput:\n\n```json\n%s\n```\n"
                     % (name, NOTES.get(name, ""), src.name, numbered,
                        json.dumps(out, ensure_ascii=False, indent=2)))
    (ROOT / "translator" / "examples.md").write_text("".join(parts), encoding="utf-8")
    print("wrote translator/examples.md")


if __name__ == "__main__":
    main()
